url : 'https://172.16.5.179:9443/magma/v1/'
cert: '\backend\configs\files\admin_operator.pem'
key : '\backend\configs\files\admin_operator.key.pem'
json_add_network: '\backend\configs\json\postnetwork.json'
json_put_network: '\backend\configs\json\putnetwork.json'
json_add_apn: '\backend\configs\json\postapn.json'
json_put_apn: '\backend\configs\json\putapn.json'
json_add_cwf: '\backend/configs/json/postcwf.json'
json_put_cellular: '/backend/configs/json/putcellular.json'
json_put_epc: '\backend/configs/json/putepc.json'
json_add_subscriber: '\backend\configs\json\postsubscriber.json'
json_put_subscriber: '\backend\configs\json\putsubscriber.json'
json_qos_policy: '\backend\configs\json\postpolicyqos.json'
json_network: '\backend/configs/json/network.json'
json_qos_profile: '\backend/configs/json/postpolicyqos.json'
json_put_federation_gateway: '\backend/configs/json/jsonputfederationgateway.json'
json_put_ngc_configuration: '\backend/configs/json/putngcconfiguration.json'
json_post_base_name: '\backend/configs/json/postbasename.json'
json_put_base_name: '\backend/configs/json/putbasename.json'